---
title: "INAR Modeling"
author: "Adam Kiehl"
date: "2/12/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(acp) # INAR model

set.seed(499)
```

Read in binned data frame:
```{r}
binned_df <- read.csv('../Data/binned_df.csv')
```

INAR model fit with acp() function:
```{r, warning=FALSE}
# use first 60 trials as training set
train_df <- binned_df %>%
  filter(trial < 60) %>%
  select(c(CA1.1, CA3.1, CA3.2, CA3.3, CA3.4, CA3.5, CA3.6, CA3.7, CA3.8, CA3.9, CA3.10, CA3.11, CA3.12, CA3.13, CA3.14, CA3.15,
           CA3.16, CA3.17, CA3.18, CA3.19, CA3.20, CA3.21)) %>%
  data.frame()

# use last 20 trials as validation set
valid_df <- binned_df %>%
  filter(trial >= 60) %>%
  select(c(CA3.1, CA3.2, CA3.3, CA3.4, CA3.5, CA3.6, CA3.7, CA3.8, CA3.9, CA3.10, CA3.11, CA3.12, CA3.13, CA3.14, CA3.15,
           CA3.16, CA3.17, CA3.18, CA3.19, CA3.20, CA3.21)) %>%
  data.frame()

# values to compare predicted values with
valid_pred <- binned_df %>%
  filter(trial >= 60) %>%
  select(CA1.1)

# fit INAR model
model <- acp(CA1.1 ~ ., data = train_df, p = 1, q = 2)
summary(model)

# caluclate MSE from predicted values
pred <- predict(model, newxdata = valid_df, newydata = valid_pred)
mean((pred - valid_pred$CA1.1)^2, na.rm = TRUE)
```

Collect p-values using for loop (experimental):
```{r}
connect <- data.frame(resp = c('CA1.1', 'CA1.2', 'CA1.3', 'CA1.4', 'CA1.5', 'CA1.6', 'CA1.7', 'CA1.8', 'CA1.9', 'CA1.10',
                                'CA1.11', 'CA1.12', 'CA1.13', 'CA1.14', 'CA1.15'),
                       CA3.1 = rep(NA, 15),
                       CA3.2 = rep(NA, 15),
                       CA3.3 = rep(NA, 15),
                       CA3.4 = rep(NA, 15),
                       CA3.5 = rep(NA, 15),
                       CA3.6 = rep(NA, 15),
                       CA3.7 = rep(NA, 15),
                       CA3.8 = rep(NA, 15),
                       CA3.9 = rep(NA, 15),
                       CA3.10 = rep(NA, 15),
                       CA3.11 = rep(NA, 15),
                       CA3.12 = rep(NA, 15),
                       CA3.13 = rep(NA, 15),
                       CA3.14 = rep(NA, 15),
                       CA3.15 = rep(NA, 15),
                       CA3.16 = rep(NA, 15),
                       CA3.17 = rep(NA, 15),
                       CA3.18 = rep(NA, 15),
                       CA3.19 = rep(NA, 15),
                       CA3.20 = rep(NA, 15),
                       CA3.21 = rep(NA, 15))

for (region in connect$resp) {
  model_df <- binned_df %>%
    select(c(region, CA3.1, CA3.2, CA3.3, CA3.4, CA3.5, CA3.6, CA3.7, CA3.8, CA3.9, CA3.10, CA3.11, CA3.12, CA3.13, CA3.14, CA3.15,
           CA3.16, CA3.17, CA3.18, CA3.19, CA3.20, CA3.21))
  model <- acp(formula(paste0(region, ' ~ .')), data = model_df, p = 1, q = 2)
  temp <- summary(model)
  p_vals <- temp$coefficients[2:22, 4]
  connect[which(connect$resp == region), ] <- c(region, p_vals)
}
```

```{r}
connect %>%
  pivot_longer(!resp, names_to = 'pred', values_to = 'p_value') %>%
  ggplot() +
  geom_tile(aes(pred, resp, fill = as.numeric(p_value))) +
  scale_fill_continuous() +
  theme(legend.position = 'None') +
  labs(title='INAR p-values', x='Predictor', y='Response')
```



