---
title: "INGARCH Modeling"
author: "Adam Kiehl"
date: "2/12/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(acp) # INAR model
library(tscount)

set.seed(499)
```

Read in binned data frame:
```{r}
binned_df <- read.csv('../Data/binned_df.csv')
```

Prepare data frame for modeling:
```{r}
gen_df <- function(train, valid, resp) {
  # generate training set
  train_df <- binned_df %>%
    filter(trial %in% as.vector(train)) %>%
    select(c(all_of(resp), CA3.1, CA3.2, CA3.3, CA3.4, CA3.5, CA3.6, CA3.7, CA3.8, CA3.9, CA3.10, CA3.11, CA3.12, CA3.13, CA3.14,
             CA3.15, CA3.16, CA3.17, CA3.18, CA3.19, CA3.20, CA3.21)) %>%
    data.frame()
  
  # generate validation set
  valid_df <- binned_df %>%
    filter(trial %in% as.vector(valid)) %>%
    select(c(CA3.1, CA3.2, CA3.3, CA3.4, CA3.5, CA3.6, CA3.7, CA3.8, CA3.9, CA3.10, CA3.11, CA3.12, CA3.13, CA3.14, CA3.15,
             CA3.16, CA3.17, CA3.18, CA3.19, CA3.20, CA3.21)) %>%
    data.frame()
  
  # values to compare predicted values with
  valid_pred <- binned_df %>%
    filter(trial %in% as.vector(valid)) %>%
    select(resp)
  
  # handle empty vectors
  zeros <- c()
  zeros <- c(zeros, which(colSums(train_df) == 0))
  zeros <- c(zeros, which(colSums(valid_df) == 0))
  if (length(zeros) > 0) {
    train_df <- train_df[, -zeros]
    valid_df <- valid_df[, -zeros]
  }
  
  # return data frames
  return(list('train_df' = train_df, 'valid_df' = valid_df, 'valid_pred' = valid_pred))
}
```

INGARCH model fit with acp() function [DOESNT WORK]:
```{r}
# # collect data frames
# dfs <- gen_df(1:10, 11, 'CA1.1')
# train_df <- dfs[['train_df']]
# valid_df <- dfs[['valid_df']]
# valid_pred <- dfs[['valid_pred']]
# remove(dfs)
# 
# # fit INGARCH model
# start <- Sys.time()
# model <- acp(CA1.1 ~ ., data = train_df, p = 2, q = 5)
# print(Sys.time() - start)
# 
# summary(model)
# 
# # calculate MSE from predicted values
# pred <- predict(model, newxdata = valid_df, newydata = valid_pred)
# mean((pred - valid_pred$CA1.1)^2, na.rm = TRUE)
```

INGARCH model fit with tsglm() function:
```{r}
# collect data frames
dfs <- gen_df(1:10, 11, 'CA1.1')
train_df <- dfs[['train_df']]
valid_df <- dfs[['valid_df']]
valid_pred <- dfs[['valid_pred']]
remove(dfs)

# fit INGARCH model
start <- Sys.time()
model <- tsglm(as.ts(train_df[, 1]), xreg = as.matrix(train_df[, -1]), 
               model = list(past_obs = 1:5, past_mean = 15), 
               link = 'log', distr = 'poisson')
print(Sys.time() - start)

summary(model)

# calculate MSE from predicted values
pred <- predict(model, n.ahead = nrow(valid_df), newxreg = valid_df)
mean((pred[['pred']] - valid_pred$CA1.1)^2, na.rm = TRUE)
```

Tuning the tsglm() function:
```{r}

```

```{r}
connect <- data.frame(resp = c('CA1.1', 'CA1.2', 'CA1.3', 'CA1.4', 'CA1.5', 'CA1.6', 'CA1.7', 'CA1.8', 'CA1.9', 'CA1.10',
                                'CA1.11', 'CA1.12', 'CA1.13', 'CA1.14', 'CA1.15'),
                       beta.1 = rep(NA, 15),
                       beta.2 = rep(NA, 15),
                       beta.3 = rep(NA, 15),
                       beta.4 = rep(NA, 15),
                       beta.5 = rep(NA, 15),
                       a.740 = rep(NA, 15),
                       CA3.1 = rep(NA, 15),
                       CA3.2 = rep(NA, 15),
                       CA3.3 = rep(NA, 15),
                       CA3.4 = rep(NA, 15),
                       CA3.5 = rep(NA, 15),
                       CA3.6 = rep(NA, 15),
                       CA3.7 = rep(NA, 15),
                       CA3.8 = rep(NA, 15),
                       CA3.9 = rep(NA, 15),
                       CA3.10 = rep(NA, 15),
                       CA3.11 = rep(NA, 15),
                       CA3.12 = rep(NA, 15),
                       CA3.13 = rep(NA, 15),
                       CA3.14 = rep(NA, 15),
                       CA3.15 = rep(NA, 15),
                       CA3.16 = rep(NA, 15),
                       CA3.17 = rep(NA, 15),
                       CA3.18 = rep(NA, 15),
                       CA3.19 = rep(NA, 15),
                       CA3.20 = rep(NA, 15),
                       CA3.21 = rep(NA, 15))

for (region in connect$resp) {
  model_df <- binned_df %>%
    filter(trial < 11) %>%
    select(c(region, CA3.1, CA3.2, CA3.3, CA3.4, CA3.5, CA3.6, CA3.7, CA3.8, CA3.9, CA3.10, CA3.11, CA3.12, CA3.13, CA3.14, CA3.15,
           CA3.16, CA3.17, CA3.18, CA3.19, CA3.20, CA3.21))
  tryCatch(
    {
      model <- tsglm(as.ts(model_df[, 1]), xreg = as.matrix(model_df[, -1]), 
               model = list(past_obs = 1:5, past_mean = 740), 
               link = 'log', distr = 'poisson')
      temp <- summary(model)
      est <- temp$coefficients$Estimate[-1]
      connect[which(connect$resp == region), ] <- c(region, est)
      print(paste('Success:', region))
    },
    error=function(cond) {
      connect[which(connect$resp == region), ] <- c(region, rep(NA, ncol(model_df) + 5))
      print(paste('Error:', region))
    }
  )
}
```

# Plot coefficient estimates from one-to-many models
```{r}
connect %>%
  pivot_longer(!resp, names_to = 'pred', values_to = 'est') %>%
  ggplot() +
  geom_tile(aes(factor(pred, levels = c('beta.1', 'beta.2', 'beta.3', 'beta.4', 'beta.5', 'a.740', names(train_df[, -1]))),
                factor(resp, levels = connect$resp), 
                fill = as.numeric(est))) +
  scale_fill_continuous() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title='INGARCH Coefficient Estimates', x='Predictor', y='Response', fill='')
```



